version: '3.4'

services:
    invoiceapp:
        image: invoiceapp
        build:
            context: .
        environment:
            - NODE_ENV=production
            - MONGO_DB=mongodb://mongo
        ports:
            - 3000:3000
        networks:
            - invoiceapp
        depends_on:
            - mongo
    mongo:
        hostname: mongo
        image: mongo
        networks:
            - invoiceapp
        volumes:
            - dbdata:/data/db

networks:
    invoiceapp:
        driver: bridge

volumes:
    dbdata:
